apiVersion: apps/v1
kind: Deployment
metadata:
  name: runbook-expert-amazonlinux
  namespace: default
  labels:
    app: runbook-expert-amazonlinux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: runbook-expert-amazonlinux-app
  template:
    metadata:
      labels:
        app: runbook-expert-amazonlinux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                #- amd64
                - arm64
      containers:
      - name: runbook-expert-amazonlinux
        image: 011285877396.dkr.ecr.eu-west-2.amazonaws.com/runbook-expert-amazonlinux:0.1
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
